jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-pr-close: 30
        days-before-stale: 365
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: This PR is stale because it has been open 365 days with
          no activity. Remove stale label or comment or this will be closed in 30
          days.
name: Close stale PR
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
